---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xuyafang.
--- DateTime: 2018/10/4 9:53
---住宅更改租金界面
BuildingSetSalaryCtrl = class('BuildingSetSalaryCtrl',UIPanel)
UIPanel:ResgisterOpen(BuildingSetSalaryCtrl)

function BuildingSetSalaryCtrl:initialize()
    UIPanel.initialize(self, UIType.PopUp, UIMode.DoNothing, UICollider.Normal)
end

function BuildingSetSalaryCtrl:bundleName()
    return "Assets/CityGame/Resources/View/BuildingSetSalaryPanel.prefab"
end

function BuildingSetSalaryCtrl:OnCreate(obj )
    UIPanel.OnCreate(self, obj)
end

function BuildingSetSalaryCtrl:Awake(go)
    self.gameObject = go
    self:_getComponent(go)

    self.luaBehaviour = self.gameObject:GetComponent('LuaBehaviour')
    self.luaBehaviour:AddClick(self.closeBtn, self._onClickCloseBtn, self)
    self.luaBehaviour:AddClick(self.okBtn, self._onClickConfim, self)
    self.wageSlider.onValueChanged:AddListener(function (value)
        local tempValue = math.floor(value)
        self:_showPercentValue(tempValue)
    end)
end

function BuildingSetSalaryCtrl:Refresh()
    self:_initData()
end
---寻找组件
function BuildingSetSalaryCtrl:_getComponent(go)
    self.closeBtn = go.transform:Find("root/closeBtn").gameObject
    self.okBtn = go.transform:Find("root/okBtn").gameObject
    self.staffNumText = go.transform:Find("root/staffNum/staffNumText"):GetComponent("Text")
    self.standardWageText = go.transform:Find("root/wage/standardWageText"):GetComponent("Text")
    self.wageSlider = go.transform:Find("root/wageSlider"):GetComponent("Slider")
    self.effectiveDateText = go.transform:Find("root/effectiveDateText"):GetComponent("Text")

    self.select50Text = go.transform:Find("root/wageLevel/00/selectText")
    self.select75Text = go.transform:Find("root/wageLevel/01/selectText")
    self.select100Text = go.transform:Find("root/wageLevel/02/selectText")
    self.simple50Text = go.transform:Find("root/wageLevel/00/Text")
    self.simple75Text = go.transform:Find("root/wageLevel/01/Text")
    self.simple100Text = go.transform:Find("root/wageLevel/02/Text")

    self.effectText = go.transform:Find("root/bg/Text01/effectText"):GetComponent("Text")
    self.totalText = go.transform:Find("root/bg/Text02/totalText"):GetComponent("Text")
end
---初始化
function BuildingSetSalaryCtrl:_initData()
    if self.m_data == nil then
        return
    end

    self.rentInput.text = self.m_data.rent
    local blackColor = "#4B4B4B"
    local rentalStr = string.format("%s<color=%s>%s</color>", getPriceString(self.m_data.rent, 24, 18), blackColor, "/D")
    self.currentRentalText.text = rentalStr

    local suggestStr = string.format("%sE<color=%s>%s</color>", getPriceString(self.m_data.suggestRent, 20, 18), blackColor, "/D")
    self.suggestRentalText.text = suggestStr

    local trueTextW = self.suggestRentalText.preferredWidth
    local pos = self.suggestRect.anchoredPosition
    self.suggestRect.anchoredPosition = Vector2.New(70 + 164 - trueTextW, pos.y)

    self.effectTime = TimeSynchronized.GetTheCurrentTime()
    self.effectiveDateText.text = self.effectTime

end
--根据选中的档位显示数据
function BuildingSetSalaryCtrl:_showPercentValue(level)
    if level == 0 then
        self.simple50Text.localScale = Vector3.zero
        self.simple75Text.localScale = Vector3.one
        self.simple100Text.localScale = Vector3.one

        self.select50Text.localScale = Vector3.one
        self.select75Text.localScale = Vector3.zero
        self.select100Text.localScale = Vector3.zero
    elseif level == 1 then
        self.simple50Text.localScale = Vector3.one
        self.simple75Text.localScale = Vector3.zero
        self.simple100Text.localScale = Vector3.one

        self.select50Text.localScale = Vector3.zero
        self.select75Text.localScale = Vector3.one
        self.select100Text.localScale = Vector3.zero
    elseif level == 2 then
        self.simple50Text.localScale = Vector3.one
        self.simple75Text.localScale = Vector3.one
        self.simple100Text.localScale = Vector3.zero

        self.select50Text.localScale = Vector3.zero
        self.select75Text.localScale = Vector3.zero
        self.select100Text.localScale = Vector3.one
    end
end
--
function BuildingSetSalaryCtrl:_onClickConfim(ins)
    if ins.m_data.callBackFunc ~= nil then
        ins.m_data.callBackFunc()
    end

    --向服务器发送请求，改变租金
    --Event.Brocast("m_ReqHouseChangeRent", ins.m_data.buildingId, inputValue)
    ins:_onClickCloseBtn(ins)
end
--
function BuildingSetSalaryCtrl:_onClickCloseBtn(ins)
    UIPanel.ClosePage()
end