---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by password.
--- DateTime: 2018/12/5 17:55
---城市信息选择框
CityToggleCtrl = class('CityToggleCtrl',UIPage)
UIPage:ResgisterOpen(CityToggleCtrl) --注册打开的方法
local CityInfoCtrlBehaviour;
local gameObject;
local close

function  CityToggleCtrl:bundleName()
    return "CityTogglePanel"
end

function CityToggleCtrl:initialize()
    UIPage.initialize(self,UIType.Normal,UIMode.HideOther,UICollider.None)--可以回退，UI打开后，隐藏其它面板
    --UIPage.initialize(self,UIType.Normal,UIMode.NeedBack,UICollider.None)--可以回退，UI打开后，不隐藏其它的UI
end

--启动事件--
function CityToggleCtrl:OnCreate(obj)
    UIPage.OnCreate(self,obj)
    gameObject = obj;
    close = nil
    CityInfoCtrlBehaviour = self.gameObject:GetComponent('LuaBehaviour');
    CityInfoCtrlBehaviour:AddClick(CityTogglePanel.backBtn,self.OnBackBtn,self);
    CityInfoCtrlBehaviour:AddClick(CityTogglePanel.companyNumBtn,self.OnCompanyNumBtn,self);
    CityTogglePanel.time.text = os.date("%m月".."\n".."%d");

    tableSort(MaterialCommodityProcess,CityTogglePanel.company)   --生成cityinfoName表格

    Event.AddListener("c_OnBtn",self.c_OnBtn,self)

end
function CityToggleCtrl:Awake(go)
    self.gameObject = go
    CityToggleCtrl.CityMaterial = {}
    CityToggleCtrl.CityMaterial = CityMaterial
    CityToggleCtrl.static.luaBehaviour = self.gameObject:GetComponent('LuaBehaviour')

    self.material = UnityEngine.UI.LoopScrollDataSource.New()  --行情
    self.material.mProvideData = CityToggleCtrl.static.MaterialProvideData
    self.material.mClearData = CityToggleCtrl.static.MaterialClearData
    CityMaterialPanel.materialScroll:ActiveLoopScroll(self.material, #self.CityMaterial)

end

--返回按钮
function CityToggleCtrl:OnBackBtn()
    UIPage.ClosePage();
end

--滑动互用
CityToggleCtrl.static.MaterialProvideData = function(transform, idx)

    idx = idx + 1
    local item = CityToggleItem:new(CityToggleCtrl.CityMaterial[idx], transform,idx)
    local materialItems = {}
    materialItems[idx] = item
end
CityToggleCtrl.static.MaterialClearData = function(transform)
end

--点击参与公司人数排序
function CityToggleCtrl:OnCompanyNumBtn(go)
    table.sort( go.CityMaterial, function (m, n) return m.companyNum > n.companyNum end)
    CityTogglePanel.materialScroll:ActiveLoopScroll(go.material, #go.CityMaterial)
end

function CityToggleCtrl:c_OnBtn(go,isoppen)
    if close ~= nil then
        CityMaterialCtrl:Close(close)
    end
    if isoppen  then
        CityMaterialCtrl:Oppen(go)
        --[[    else
                CityMaterialCtrl:Close(go)]]
    end
    close = go
    --[[    for i = 1, CityMaterialPanel.company.transform.childCount do
             destroy(CityMaterialPanel.company.gameObject:GetComponent("RectTransform"):GetChild(i-1).gameObject)
        end
        --tableSort(MaterialCommodityProcess,CityMaterialPanel.company)]]
end

--排序方法
--生成预制
function CityToggleCtrl:_createCityInfoPab(path,parent)
    local prefab = UnityEngine.Resources.Load(path);
    local go = UnityEngine.GameObject.Instantiate(prefab);
    local rect = go.transform:GetComponent("RectTransform");
    go.transform:SetParent(parent.transform);
    rect.transform.localScale = Vector3.one;
    return rect
end
--打开曲线图
function CityToggleCtrl:Oppen(go)
    go.transform.sizeDelta = Vector2.New(1920,560)
    go.change:Change(go.element,560)
    go.gameObject:SetActive(true)
end
--关闭曲线图
function CityToggleCtrl:Close(go)
    go.transform.sizeDelta = Vector2.New(1920,130)
    go.change:Change(go.element,130)
    go.gameObject:SetActive(false)
end