---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xuyafang.
--- DateTime: 2018/9/30 16:30
---Total score prompt box
FixedTotalScoreCtrl = class('FixedTotalScoreCtrl',UIPanel)
UIPanel:ResgisterOpen(FixedTotalScoreCtrl)

function FixedTotalScoreCtrl:initialize()
    UIPanel.initialize(self, UIType.Fixed, UIMode.DoNothing, UICollider.Normal)
end

function FixedTotalScoreCtrl:bundleName()
    return "Assets/CityGame/Resources/View/Common/FixedTotalTip.prefab"
end

function FixedTotalScoreCtrl:OnCreate(obj)
    UIPanel.OnCreate(self, obj)
end

function FixedTotalScoreCtrl:Awake(go)
    self:_getComponent(go)
    self.luaBehaviour = go:GetComponent('LuaBehaviour')
    self.luaBehaviour:AddClick(self.infoRootBtn.gameObject, function ()
        self:Hide()
    end, self)
end

function FixedTotalScoreCtrl:Refresh()
    self:_initData()
end

---Find components
function FixedTotalScoreCtrl:_getComponent(go)
    self.infoRootBtn = go.transform:Find("infoRootBtn")
    self.tipRect = go.transform:Find("infoRootBtn/bg"):GetComponent("RectTransform")
    self.infoText = go.transform:Find("infoRootBtn/bg/Text"):GetComponent("Text")
end
---initialization
function FixedTotalScoreCtrl:_initData()
    if self.m_data.pos ~= nil then
        self.tipRect.position = self.m_data.pos
    end
    if self.m_data.type == "House" then
        self.infoText.text = GetLanguage(4301009)
    elseif self.m_data.type == "Goods" then
        self.infoText.text = GetLanguage(4301010)
    end
end


