---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Fisher.
--- DateTime: 2019/5/22 15:20
---建筑信息商品详情
GoodsTypeBoxCtrl = class('GoodsTypeBoxCtrl',UIPanel)
UIPanel:ResgisterOpen(GoodsTypeBoxCtrl)

local ToNumber = tonumber
local StringSun = string.sub
function GoodsTypeBoxCtrl:initialize()
    UIPanel.initialize(self,UIType.PopUp,UIMode.DoNothing,UICollider.Normal)
end

function GoodsTypeBoxCtrl:bundleName()
    return "Assets/CityGame/Resources/View/GoodsTypeBoxPanel.prefab"
end
function GoodsTypeBoxCtrl:OnCreate(obj)
    UIPanel.OnCreate(self,obj)
end

function GoodsTypeBoxCtrl:Awake(go)
    self.gameObject = go
    self:_getComponent(go)
    self.luaBehaviour = self.gameObject:GetComponent('LuaBehaviour')
    self.luaBehaviour:AddClick(self.bgBtn.gameObject,self._clickBgBtn,self)
end

function GoodsTypeBoxCtrl:Refresh()
    self:_language()
    self:initializeUiInfoData()
end

function GoodsTypeBoxCtrl:Hide()
    UIPanel.Hide(self)
end
-------------------------------------------------------------获取组件-------------------------------------------------------------------------------
function GoodsTypeBoxCtrl:_getComponent(go)
    self.bgBtn = go.transform:Find("bg")
    --content
    self.topName = go.transform:Find("content/top/topBg/topName"):GetComponent("Text")
    --基础生产速度
    self.basicProduceRate = go.transform:Find("content/basicProduceRate")
    self.basicProduceRateText = go.transform:Find("content/basicProduceRate/Text"):GetComponent("Text")
    self.basicProduceRateValue = go.transform:Find("content/basicProduceRate/basicProduceRateImg/basicProduceRateValue"):GetComponent("Text")
    self.basicProduceRateUnit = go.transform:Find("content/basicProduceRate/basicProduceRateImg/basicProduceRateValue/unit"):GetComponent("Text")

    --生产速度加成
    self.produceBounus = go.transform:Find("content/produceBounus")
    self.produceBounusText = go.transform:Find("content/produceBounus/Text"):GetComponent("Text")
    self.produceBounusValue = go.transform:Find("content/produceBounus/produceBounusImg/produceBounusValue"):GetComponent("Text")
    self.produceBounusUnit = go.transform:Find("content/produceBounus/produceBounusImg/produceBounusValue/unit"):GetComponent("Text")

    --基础品质
    self.basicQuality = go.transform:Find("content/basicQuality")
    self.basicQualityText = go.transform:Find("content/basicQuality/Text"):GetComponent("Text")
    self.basicQualityValue = go.transform:Find("content/basicQuality/basicQualityImg/basicQualityValue"):GetComponent("Text")

    --品质加成
    self.qualityAddition = go.transform:Find("content/qualityAddition")
    self.qualityAdditionText = go.transform:Find("content/qualityAddition/Text"):GetComponent("Text")
    self.qualityAdditionValue = go.transform:Find("content/qualityAddition/qualityAdditionImg/qualityAdditionValue"):GetComponent("Text")
    self.qualityAdditionUnit = go.transform:Find("content/qualityAddition/qualityAdditionImg/qualityAdditionValue/unit"):GetComponent("Text")

    --知名度
    self.popularity = go.transform:Find("content/popularity")
    self.popularityText = go.transform:Find("content/popularity/Text"):GetComponent("Text")
    self.popularityValue = go.transform:Find("content/popularity/popularityImg/popularityValue"):GetComponent("Text")
end
------------------------------------------------------------初始化函数--------------------------------------------------------------------------------
--初始化UI
function GoodsTypeBoxCtrl:initializeUiInfoData()
    self.topName.text = GetLanguage(self.m_data.itemId).."生产技术"
    if ToNumber(StringSun(self.m_data.itemId,1,2)) == 21 then
        --原料
        self.basicQuality.gameObject:SetActive(false)
        self.qualityAddition.gameObject:SetActive(false)
        self.popularity.gameObject:SetActive(false)

        self.basicProduceRateValue.text = self.m_data.numOneSec
        self.produceBounusValue.text = (self.m_data.eva.lv - 1) / 100
        --self.produceBounusValue.text = 1 / (self.m_data.numOneSec * (1 + (self.m_data.eva.lv - 1) / 100))
    elseif ToNumber(StringSun(self.m_data.itemId,1,2)) == 22 then
        --商品
        self.basicQuality.gameObject:SetActive(true)
        self.qualityAddition.gameObject:SetActive(true)
        self.popularity.gameObject:SetActive(true)

        self.basicProduceRateValue.text = self.m_data.numOneSec
        self.produceBounusValue.text = self.m_data.addNumOneSec
        self.basicQualityValue.text = self.m_data.quality
        self.qualityAdditionValue.text = self.m_data.addQuality
        self.popularityValue.text = self.m_data.brand
    end
end
--设置多语言
function GoodsTypeBoxCtrl:_language()
    self.basicProduceRateText.text = "基础生产速度"
    self.produceBounusText.text = "生产速度加成"
    self.basicQualityText.text = "基础品质"
    self.qualityAdditionText.text = "品质加成"
    self.popularityText.text = "知名度"
    self.basicProduceRateUnit.text = "per/s"
    self.produceBounusUnit.text = "%"
    self.qualityAdditionUnit.text = "%"
end
------------------------------------------------------------点击函数--------------------------------------------------------------------------------
--关闭
function GoodsTypeBoxCtrl:_clickBgBtn()
    PlayMusEff(1002)
    UIPanel.ClosePage()
end