---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Tina.
--- DateTime: 2019/2/19 17:25
---

GuildApplyCtrl = class("GuildApplyCtrl", UIPanel)
UIPanel:ResgisterOpen(GuildApplyCtrl)

function GuildApplyCtrl:initialize(go)
    UIPanel.initialize(self, UIType.PopUp, UIMode.NeedBack, UICollider.None)
end

function GuildApplyCtrl:bundleName()
    return "Assets/CityGame/Resources/View/GuildApplyPanel.prefab"
end

function GuildApplyCtrl:OnCreate(go)
    UIPanel.OnCreate(self, go)

    GuildApplyCtrl.luaBehaviour = self.gameObject:GetComponent("LuaBehaviour")
    GuildApplyCtrl.luaBehaviour:AddClick(GuildApplyPanel.backBtn, function ()
        PlayMusEff(1002)
        UIPanel.ClosePage()
    end)
end

function GuildApplyCtrl:Awake()
    GuildApplyCtrl.static.guildApplyTab = {}
    self.guildApplySource = UnityEngine.UI.LoopScrollDataSource.New()
    self.guildApplySource.mProvideData = GuildApplyCtrl.static.GuildApplyProvideData
    self.guildApplySource.mClearData = GuildApplyCtrl.static.GuildApplyClearData
end

function GuildApplyCtrl:Active()
    UIPanel.Active(self)
    self:_addListener()

    -- 多语言
    GuildApplyPanel.panelNameText.text = GetLanguage(12060015)
    GuildApplyPanel.noContentText.text = GetLanguage(12060016)
end

-- 监听Model层网络回调
function GuildApplyCtrl:_addListener()
    Event.AddListener("c_DelJoinReq", self.c_DelJoinReq, self)
    Event.AddListener("c_NewJoinReq", self.c_NewJoinReq, self)
end

--注销model层网络回调
function GuildApplyCtrl:_removeListener()
    Event.RemoveListener("c_DelJoinReq", self.c_DelJoinReq, self)
    Event.RemoveListener("c_NewJoinReq", self.c_NewJoinReq, self)
end

function GuildApplyCtrl:Refresh()
    self:initInsData()
    self:_showView()
end

-- 打开model
function GuildApplyCtrl:initInsData()
    DataManager.OpenDetailModel(GuildApplyModel, OpenModelInsID.GuildApplyCtrl)
    --DataManager.DetailModelRpcNoRet(OpenModelInsID.GuildApplyCtrl, "m_GetSocietyInfo", {id = self.m_data})
end

function GuildApplyCtrl:Hide()
    self:_removeListener()
    UIPanel.Hide(self)
end

-- 显示申请列表
function GuildApplyCtrl:_showView()
    local societyInfo = DataManager.GetGuildInfo()
    if societyInfo and societyInfo.reqs then
        GuildApplyCtrl.societyApplyInfo = societyInfo.reqs
        GuildApplyPanel.guildInfoScroll:ActiveLoopScroll(self.guildApplySource, #GuildApplyCtrl.societyApplyInfo, "View/Guild/GuildApplyItem")
        if #GuildApplyCtrl.societyApplyInfo == 0 then
            GuildApplyPanel.noContentImage.localScale = Vector3.one
        else
            GuildApplyPanel.noContentImage.localScale = Vector3.zero
        end
    else
        GuildApplyPanel.noContentImage.localScale = Vector3.one
    end
end

-- 滑动复用
GuildApplyCtrl.static.GuildApplyProvideData = function(transform, idx)
    idx = idx + 1
    local transformId = transform:GetInstanceID()
    if GuildApplyCtrl.static.guildApplyTab[transformId] then
        GuildApplyCtrl.static.guildApplyTab[transformId]:CloseAvatar()
    end
    GuildApplyCtrl.static.guildApplyTab[transformId] = GuildApplyItem:new(transform, GuildApplyCtrl.societyApplyInfo[idx])
end

GuildApplyCtrl.static.GuildApplyClearData = function(transform)

end

-- 网络回调
-- 刷新申请列表
function GuildApplyCtrl:c_DelJoinReq(joinReq)
    if joinReq.handleId == DataManager.GetMyOwnerID() then
        if joinReq.serverFlag then
            if joinReq.handleFlag then
                Event.Brocast("SmallPop", "已同意申请", 80)
            else
                Event.Brocast("SmallPop", "已拒绝申请", 80) --  .. joinReq.playerId
            end
        else
            Event.Brocast("SmallPop", "已有公会", 80)
        end
    end
    GuildApplyPanel.guildInfoScroll:ActiveLoopScroll(self.guildApplySource, #GuildApplyCtrl.societyApplyInfo, "View/Guild/GuildApplyItem")
    if #GuildApplyCtrl.societyApplyInfo == 0 then
        GuildApplyPanel.noContentImage.localScale = Vector3.one
    else
        GuildApplyPanel.noContentImage.localScale = Vector3.zero
    end
end

-- 新增入会请求
function GuildApplyCtrl:c_NewJoinReq(joinReq)
    --GuildApplyPanel.guildInfoScroll:ActiveLoopScroll(self.guildApplySource, #GuildApplyCtrl.societyApplyInfo, "View/Guild/GuildApplyItem")
    self:_showView()
end