---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ljw.
--- DateTime: 2019/4/23 16:00
---


local transform
MainRenTableWarehousePanel = {}
local this = MainRenTableWarehousePanel

function MainRenTableWarehousePanel.Awake(obj)
    transform = obj.transform
    this.InitPanel()
end

function MainRenTableWarehousePanel.InitPanel()
    this.topnameText = transform:Find("contentRoot/top/topNameText"):GetComponent("Text")
    this.backBtn = transform:Find("contentRoot/top/backBtn")

    this.setBtn = transform:Find("contentRoot/mid/setBtn")

    this.spaceText = transform:Find("contentRoot/mid/left/count"):GetComponent("Text")
    this.spacenameText = transform:Find("contentRoot/mid/left/space"):GetComponent("Text")

    this.timeText = transform:Find("contentRoot/mid/mid/count"):GetComponent("Text")
    this.timenameText = transform:Find("contentRoot/mid/mid/time"):GetComponent("Text")

    this.priceText = transform:Find("contentRoot/mid/right/count"):GetComponent("Text")
    this.pricenameText = transform:Find("contentRoot/mid/right/price"):GetComponent("Text")

    this.earningScroll = transform:Find("contentRoot/down/Scroll View/Viewport"):GetComponent("ActiveLoopScrollRect")
end