---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by password.
--- DateTime: 2019/7/26 16:03
--- 上架市场数据界面
ShelfMarketDataCtrl = class('ShelfMarketDataCtrl',UIPanel)
UIPanel:ResgisterOpen(ShelfMarketDataCtrl)

local shelfMarketDataBehaviour
function ShelfMarketDataCtrl:bundleName()
    return "Assets/CityGame/Resources/View/PromoteCompanyPanel.prefab"
end

function ShelfMarketDataCtrl:initialize()
    UIPanel.initialize(self,UIType.Normal,UIMode.HideOther,UICollider.None)--可以回退，UI打开后，隐藏其它面板
    --UIPanel.initialize(self,UIType.PopUp,UIMode.NeedBack,UICollider.None)--可以回退，UI打开后，不隐藏其它的UI
end

function ShelfMarketDataCtrl:Awake()
    shelfMarketDataBehaviour = self.gameObject:GetComponent('LuaBehaviour')
    shelfMarketDataBehaviour:AddClick(PromoteCompanyPanel.back,self.OnBack,self)
end

function ShelfMarketDataCtrl:Active()
    UIPanel.Active(self)
end

function ShelfMarketDataCtrl:Refresh()
    DataManager.OpenDetailModel(PromoteCompanyModel,self.m_data.insId)
    DataManager.DetailModelRpcNoRet(self.m_data.insId, 'm_detailPublicFacility',self.m_data.insId)
    self:initData()
end

function ShelfMarketDataCtrl:Hide()
    UIPanel.Hide(self)
end

function ShelfMarketDataCtrl:OnCreate(obj)
    UIPanel.OnCreate(self,obj)
    self:_getComponent(obj)
end

--获取组件
function ShelfMarketDataCtrl:_getComponent(go)

end

--初始化数据
function ShelfMarketDataCtrl:initData()

end

--返回
function ShelfMarketDataCtrl:OnBack()
    UIPanel.ClosePage()
end
