---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xuyafang.
--- DateTime: 2018/11/21 16:11
---
UIBubbleCtrl = class('UIBubbleCtrl',UIPage)
UIPage:ResgisterOpen(UIBubbleCtrl)

UIBubbleCtrl.static.GroundAucSoonObjPath = "View/Items/BuildingBubbleItems/UIBubbleGroundAucSoonItem"  --即将拍卖
UIBubbleCtrl.static.GroundAucNowObjPath = "View/Items/BuildingBubbleItems/UIBubbleGroundAucNowItem"  --正在拍卖
UIBubbleCtrl.static.NpcFlowObjPath = "View/Items/BuildingBubbleItems/UIBubbleNpcFlowItem"  --人流量
UIBubbleCtrl.static.SellRentObjPath = "View/Items/BuildingBubbleItems/UIBubbleTransAndBuildingItem"  --土地交易气泡
UIBubbleCtrl.static.Trans = nil

function UIBubbleCtrl:initialize()
    UIPage.initialize(self, UIType.Fixed, UIMode.HideOther, UICollider.None)
end

function UIBubbleCtrl:bundleName()
    return "Assets/CityGame/Resources/View/UIBubblePanel.prefab"
end

function UIBubbleCtrl:OnCreate(obj)
    UIPage.OnCreate(self, obj)
end

function UIBubbleCtrl:Awake(go)
    --self.gameObject = go
    UIBubbleCtrl.static.Trans = self.gameObject
    self:_addListener()
end

function UIBubbleCtrl:Refresh()
    --self:_initFunc()
end
function UIBubbleCtrl:_addListener()
    Event.AddListener("c_RefreshItems", self._refreshItems, self)
    Event.AddListener("c_HideGroundBubble", self._hideAllItems, self)
    Event.AddListener("c_ShowGroundBubble", self._showAllItems, self)
end
function UIBubbleCtrl:_removeListener()
    Event.RemoveListener("c_RefreshItems", self._refreshItems, self)
    Event.RemoveListener("c_HideGroundBubble", self._hideAllItems, self)
    Event.RemoveListener("c_ShowGroundBubble", self._showAllItems, self)
end

function UIBubbleCtrl._cameraLateUpdate()
    if UIBubbleMgr.startFlowCam == nil or UIBubbleMgr.startFlowCam == false then
        return
    end
    Event.Brocast("c_RefreshLateUpdate")
end

--拍卖气泡
function UIBubbleCtrl.createGroundAucData(data)
    if data == nil then
        return
    end
    if UIBubbleCtrl.bubbleMgr == nil then
        UIBubbleCtrl.bubbleMgr = UIBubbleMgr:new(UIBubbleCtrl.static.Trans)
    end

    if data.bubbleType == UIBubbleType.GroundAuc then
        UIBubbleCtrl.bubbleMgr:initGroundAucBubbles(data)
    end
end

--更新数据
function UIBubbleCtrl:_refreshItems(datas)
    self.bubbleMgr:_refreshItems(datas)
end

--隐藏所有气泡
function UIBubbleCtrl:_hideAllItems()
    self.bubbleMgr:_hideAllItems()
end
--显示所有气泡
function UIBubbleCtrl:_showAllItems()
    self.bubbleMgr:_showAllItems()
end

----
--打开拍卖界面
function UIBubbleCtrl._openGroundAucCtrl(index)
    if index == 1 then
        if self.bubbleMgr:getNowItem() ~= nil then
            self.bubbleMgr:getNowItem():_openGroundAucFunc()
        end
        return
    end
    if index == 0 then
        if self.bubbleMgr:getSoonItem() ~= nil then
            self.bubbleMgr:getSoonItem():_openGroundAucFunc()
        end
        return
    end
end
--通过类型获取一个气泡
function UIBubbleCtrl.getBubbleByType(bubbleType, groundState, serverPos)
    if bubbleType == UIBubbleType.GroundTrans or bubbleType == UIBubbleType.BuildingSelf then
        local data = {bubbleType = bubbleType, groundState = groundState}
        local obj = UIBubbleCtrl._getBubbleObj(bubbleType)
        if serverPos ~= nil then
            data.blockId = TerrainManager.GridIndexTurnBlockID(serverPos)
            obj.name = "bubble "..serverPos.x..serverPos.y
        end
        local bubbleItem = UIBubbleTransAndBuildingItem:new(data, obj)
        return bubbleItem
    end
end
function UIBubbleCtrl._getBubbleObj(type)
    local go
    if type == UIBubbleType.GroundTrans or type == UIBubbleType.BuildingSelf then
        if UIBubbleCtrl.static.sellRentPrefab == nil then
            UIBubbleCtrl.static.sellRentPrefab = UnityEngine.Resources.Load(UIBubbleCtrl.static.SellRentObjPath)
        end
        go = UnityEngine.GameObject.Instantiate(UIBubbleCtrl.static.sellRentPrefab)
    else
        --拍卖类型的预制
    end
    local temp = UIBubbleCtrl.static.Trans
    go.transform:SetParent(temp)
    go.transform.localScale = Vector3.one
    return go
end