---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by password.
--- DateTime: 2019/6/3 11:10
---User Manual
UserNanualCtrl = class('UserNanualCtrl',UIPanel)
UIPanel:ResgisterOpen(UserNanualCtrl)

local userNanualBehaviour;

function  UserNanualCtrl:bundleName()
    return "Assets/CityGame/Resources/View/UserNanualPanel.prefab"
end

function UserNanualCtrl:initialize()
    UIPanel.initialize(self,UIType.Normal,UIMode.HideOther,UICollider.None)--You can go back and hide other panels after the UI opens
    --UIPanel.initialize(self,UIType.Normal,UIMode.NeedBack,UICollider.None)--Can go back, after the UI is opened, other UI is not hidden
end

function UserNanualCtrl:OnCreate(obj)
    UIPanel.OnCreate(self,obj)
end

function UserNanualCtrl:Awake()
    userNanualBehaviour = self.gameObject:GetComponent('LuaBehaviour');
    userNanualBehaviour:AddClick(UserNanualPanel.back,self.OnBack,self)
    userNanualBehaviour:AddClick(UserNanualPanel.agree,self.OnAgree,self)
end

function UserNanualCtrl:Active()
    UIPanel.Active(self)

    UserNanualPanel.content.text = GetLanguage(35010001)
end

function UserNanualCtrl:Hide()
    UIPanel.Hide(self)
end

--return
function UserNanualCtrl:OnBack()
    PlayMusEff(1002)
    UIPanel.ClosePage()
end

function UserNanualCtrl:OnAgree()
    PlayMusEff(1002)
    --Agree user guidelines
    LoginPanel.norm.isOn = true
    UIPanel.ClosePage()
end