---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by password.
--- DateTime: 2019/7/27 11:29
--- 使用数据面板
UserDataCtrl = class('UserDataCtrl',UIPanel)
UIPanel:ResgisterOpen(UserDataCtrl)

local userDataCtrlBehaviour
function UserDataCtrl:bundleName()
    return "Assets/CityGame/Resources/View/ChooseDataTypePanel.prefab"
end

function UserDataCtrl:initialize()
    UIPanel.initialize(self,UIType.Normal,UIMode.HideOther,UICollider.None)--可以回退，UI打开后，隐藏其它面板
    --UIPanel.initialize(self,UIType.PopUp,UIMode.NeedBack,UICollider.None)--可以回退，UI打开后，不隐藏其它的UI
end

function UserDataCtrl:Awake()
    userDataCtrlBehaviour = self.gameObject:GetComponent('LuaBehaviour')
    userDataCtrlBehaviour:AddClick(self.bg,self.OnBg,self)
    userDataCtrlBehaviour:AddClick(self.btn,self.OnBtn,self)

    self.input.onValueChange:AddListener(function()
        self:OnInput()
    end)
    self.slider.onValueChange:AddListener(function()
        self:OnSlider()
    end)
end

function UserDataCtrl:Active()
    UIPanel.Active(self)
    self.name = GetLanguage(24020009)
end

function UserDataCtrl:Refresh()
    self:initData()
end

function UserDataCtrl:Hide()
    UIPanel.Hide(self)
end

function UserDataCtrl:OnCreate(obj)
    UIPanel.OnCreate(self,obj)
    self:_getComponent(obj)
end

--获取组件
function UserDataCtrl:_getComponent(go)
    self.bg = go.transform:Find("bg").gameObject
    self.name = go.transform:Find("content/name"):GetComponent("Text")
    self.dataName = go.transform:Find("content/top/bg/barnd/Text"):GetComponent("Text")
    self.impact = go.transform:Find("content/top/bg/Text"):GetComponent("Text")
    self.quantity = go.transform:Find("content/quantity"):GetComponent("Text")
    self.input = go.transform:Find("content/quantity/inputBg/input"):GetComponent("InputField")
    self.slider = go.transform:Find("content/quantity/inputBg/input/Slider"):GetComponent("Slider")
    self.btn =  go.transform:Find("content/btn").gameObject
    self.btnText =  go.transform:Find("content/btn/Text"):GetComponent("Text")
end

--初始化数据
function UserDataCtrl:initData()
    --if self.m_data.myOwner then
    --    self.btnText = GetLanguage()
    --else
    --    self.btnText = GetLanguage()
    --end
   self.slider.max = self.m_data.num
end

--返回
function UserDataCtrl:OnBg()
    UIPanel.ClosePage()
end

function UserDataCtrl:OnInput()
    if self.input.text == "" then
        return
    end
    if tonumber(self.input.text) > self.m_data.num then
        self.input.text = self.m_data.num
    end
    self.slider.value = tonumber(self.input.text)
end

function UserDataCtrl:OnSlider()
    self.input.text = self.slider.value
end

function UserDataCtrl:OnBtn()

end
