---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xuyafang.
--- DateTime: 2019/5/27 11:37
---
FlightSelectPlaceItem = class('FlightSelectPlaceItem')

--Initialization method
function FlightSelectPlaceItem:initialize(viewRect, data)
    self.viewRect = viewRect.transform

    self.btn = self.viewRect:Find("btn"):GetComponent("Button")
    self.Text = self.viewRect:Find("Text"):GetComponent("Text")

    self.btn.onClick:RemoveAllListeners()
    self.btn.onClick:AddListener(function ()
        Event.Brocast("FlightChoosePlaceEvent", data)
    end)

    self:initData(data)
end
--Refresh data
function FlightSelectPlaceItem:initData(data)
    self.Text.text = string.format("%s<size=%d>(%s)</size>", data.value, 30, data.flightCode)
end
--
function FlightSelectPlaceItem:Close()

end

