---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fisher.
--- DateTime: 2019/2/16 16:51
---
BuildingBaseCtrl = class('BuildingBaseCtrl',UIPanel)
UIPanel:ResgisterOpen(BuildingBaseCtrl)  --注册打开方法

--生成itemPrefab
function BuildingBaseCtrl:CreateGoodsItems(DataInfo,itemPrefab,itemRoot,className,behaviour,buildingId,instanceTable)
    if not DataInfo then
        return
    end
    for key,value in pairs(DataInfo) do
        local obj = BuildingBaseCtrl.loadingItemPrefab(itemPrefab,itemRoot)
        local itemGoodsIns = className:new(value,obj,behaviour,key,buildingId)
        table.insert(instanceTable,itemGoodsIns)
    end
end
--获取仓库已用总容量
function BuildingBaseCtrl:GatWarehouseCapacity(DataTable)
    --仓库占用容量
    local warehouseCapacity = 0
    --仓库里锁着的容量
    local lockedCapacity = BuildingBaseCtrl.getLockedNum(DataTable)
    if not DataTable.inHand then
        warehouseCapacity = warehouseCapacity + lockedCapacity
        return warehouseCapacity
    else
        for key,value in pairs(DataTable.inHand) do
            warehouseCapacity = warehouseCapacity + value.n
        end
        warehouseCapacity = warehouseCapacity + lockedCapacity
        return warehouseCapacity
    end
end
--获取仓库容量
function BuildingBaseCtrl:GetWarehouseNum(DataTable)
    local warehouseNum = 0
    if not DataTable.inHand then
        return warehouseNum
    else
        for key,value in pairs(DataTable.inHand) do
            warehouseNum = warehouseNum + value.n
        end
        return warehouseNum
    end
end
--退出时清空界面及数据
function BuildingBaseCtrl:CloseDestroy(DataTable)
    if DataTable == nil and DataTable == {} then
        return
    else
        for key,valueObj in pairs(DataTable) do
            valueObj:closeEvent()
            destroy(valueObj.prefab.gameObject)
        end
    end
end







------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--加载实例化Prefab
function BuildingBaseCtrl.loadingItemPrefab(itemPrefab,itemRoot)
    local obj = UnityEngine.GameObject.Instantiate(itemPrefab)
    local objRect = obj.transform:GetComponent("RectTransform");
    obj.transform:SetParent(itemRoot.transform)
    objRect.transform.localScale = Vector3.one;
    obj.transform:SetSiblingIndex(1)
    obj:SetActive(true)
    return obj
end
--获取仓库锁着的容量
function BuildingBaseCtrl.getLockedNum(DataTable)
    local lockedNum = 0
    if not DataTable.inHand then
        return lockedNum
    end
    if not DataTable.locked then
        return lockedNum
    end
    for key,value in pairs(DataTable.locked) do
        lockedNum = lockedNum + value.n
    end
    return lockedNum
end
--架子隐藏和显示
function BuildingBaseCtrl.shelfImgSetActive(table,num)
    if not table then
        return
    end
    for key,valueObj in pairs(table) do
        if key % num == 1 then
            valueObj.shelfImg:SetActive(true)
        else
            valueObj.shelfImg:SetActive(false)
        end
    end
end
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------




