---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by password.
--- DateTime: 2018/12/25 15:45
---建筑人才item
local class = require 'Framework/class'
require('Framework/UI/UIPage')
BuildingTalentItem = class('BuildingTalentItem')

--初始化方法   数据（读配置表）
function BuildingTalentItem:initialize(prefab,inluabehaviour,id,DataInfo)
    self.prefab = prefab;
    self._luabehaviour = inluabehaviour;
    self.id = id
    self.dataInfo = DataInfo
    self.name = self.prefab.transform:Find("budilingName").gameObject:GetComponent("Text");
    self.slider =  self.prefab.transform:Find("Slider").gameObject:GetComponent("Slider")
    self.time =  self.prefab.transform:Find("Slider/time").gameObject:GetComponent("Text")
    self.clickView =  self.prefab.transform:Find("clickView").gameObject   --点击查看
    self.delBtn =  self.prefab.transform:Find("Xbtn")

    --self.name.text = name

    self._luabehaviour:AddClick(self.delBtn.gameObject,self.OnDelBtn,self);
    self._luabehaviour:AddClick(self.clickView,self.OnClickView,self);

end

function BuildingTalentItem:OnDelBtn(go)
    local data = {}
    data.titleInfo = "REMINDER"
    data.contentInfo = "Whether to terminate cooperation"
    data.tipInfo = "(Talent's bonus attribute will disappear!)"
    data.btnCallBack = function ()
        TalentMiningCtrl:_delTalent(go.id)
        --UIPage.ClosePage()
    end
    ct.OpenCtrl('BtnDialogPageCtrl',data)
end

function BuildingTalentItem:OnClickView(go)
    Event.Brocast("SmallPop","Successful operation",300)
end

--刷新id
function BuildingTalentItem:RefreshID(id)
    self.id = id
end