---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mengpengfei.
--- DateTime: 2019/5/17 16:06
---加工厂建筑信息
processingFactoryItem = class('processingFactoryItem')

function processingFactoryItem:initialize(dataInfo,prefab,luaBehaviour)
    self.dataInfo = dataInfo
    self.prefab = prefab

    self.processingIntroduceBtn = prefab.transform:Find("processingIntroduceBtn")
    self.processingText = prefab.transform:Find("processingIntroduceBtn/processingText"):GetComponent("Text")
    self.basicProduceRateTextBtn = prefab.transform:Find("basicProduceRateText"):GetComponent("Text")
    self.produceBounusTextBtn = prefab.transform:Find("basicProduceRateText/symbol/produceBounusText"):GetComponent("Text")
    self.basicQualityTextBtn = prefab.transform:Find("basicQualityText"):GetComponent("Text")
    self.qualityAdditionTextBtn = prefab.transform:Find("basicQualityText/symbol/qualityAdditionText"):GetComponent("Text")
    self.popolarityTextBtn = prefab.transform:Find("popolarityText"):GetComponent("Text")

    self:language()
end
function processingFactoryItem:language()
    self.processingText.text = "产品"
    self.basicProduceRateTextBtn.text = "基本的生产速度"
    self.produceBounusTextBtn.text = "生产加成"
    self.basicQualityTextBtn.text = "基本质量"
    self.qualityAdditionTextBtn.text = "质量加成"
    self.popolarityTextBtn.text = "知名度"
end