---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xuyafang.
--- DateTime: 2019/2/27 18:13
---小地图搜索类型
MapSearchTypeNonePageItem = class('MapSearchTypeNonePageItem', MapSearchTypeItemBase)

--选中了类型中的某一个
function MapSearchTypeNonePageItem:refreshShow(isSelect)
    if isSelect == true then
        if self.isSelect == false then
            self.selectFunc()  --由未选中变为选中状态
        end
        self.select.localScale = Vector3.one
        self.disSelect.localScale = Vector3.zero
    else
        self.select.localScale = Vector3.zero
        self.disSelect.localScale = Vector3.one
    end
    self.loadBtnTran.transform.localScale = Vector3.one
    self.isSelect = isSelect
end
--点击事件
function MapSearchTypeNonePageItem:_clickFunc()
    if self.isSelect == true then
        Event.Brocast("c_MapSearchCancelSelect", self.data.typeId)  --取消选中状态
    else
        Event.Brocast("c_MapSearchSelectType", self.data.typeId)  --播报事件，选中自己
    end
end