---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by password.
--- DateTime: 2019/7/25 15:05
--- 市场数据DetailPart
DataBaseDetailPart = class('DataBaseDetailPart', BasePartDetail)
--
function DataBaseDetailPart:PrefabName()
    return "DataBaseDetailPart"
end
--
function  DataBaseDetailPart:_InitEvent()

end
--
function DataBaseDetailPart:_InitClick(mainPanelLuaBehaviour)
    self.m_LuaBehaviour = mainPanelLuaBehaviour
end
--
function DataBaseDetailPart:_ResetTransform()

end
--
function DataBaseDetailPart:_RemoveEvent()

end
--
function DataBaseDetailPart:_RemoveClick()
end

function DataBaseDetailPart:Show(data)
    BasePartDetail.Show(self)
end
function DataBaseDetailPart:Hide()
    BasePartDetail.Hide(self)
end
--
function DataBaseDetailPart:RefreshData(data)

end

--
function DataBaseDetailPart:_InitTransform()
    self:_getComponent(self.transform)

end
--
function DataBaseDetailPart:_getComponent(transform)
    self.empty = transform:Find("contentRoot/empty")
    self.emptyText = transform:Find("contentRoot/empty/Image/Text"):GetComponent("Text")
    self.scrollView = transform:Find("contentRoot/Scroll View")
    self.content = transform:Find("contentRoot/Scroll View/Viewport/Content"):GetComponent("RectTransform")
end
--
function DataBaseDetailPart:_initFunc()

end
