---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by password.
--- DateTime: 2019/7/25 16:13
---数据出售DetailPart
DataSaleDetailPart = class('DataSaleDetailPart', BasePartDetail)
--
function DataSaleDetailPart:PrefabName()
    return "DataSaleDetailPart"
end
--
function  DataSaleDetailPart:_InitEvent()

end
--
function DataSaleDetailPart:_InitClick(mainPanelLuaBehaviour)
    self.m_LuaBehaviour = mainPanelLuaBehaviour
end
--
function DataSaleDetailPart:_ResetTransform()

end
--
function DataSaleDetailPart:_RemoveEvent()

end
--
function DataSaleDetailPart:_RemoveClick()
end

function DataSaleDetailPart:Show(data)
    BasePartDetail.Show(self)
end
function DataSaleDetailPart:Hide()
    BasePartDetail.Hide(self)
end
--
function DataSaleDetailPart:RefreshData(data)

end

--
function DataSaleDetailPart:_InitTransform()
    self:_getComponent(self.transform)

end

--
function DataSaleDetailPart:_getComponent(transform)
    self.empty = transform:Find("contentRoot/empty")
    self.tipText = transform:Find("contentRoot/empty/tipText"):GetComponent("Text")
    self.emptyAdd = transform:Find("contentRoot/empty/add").gameObject
    self.noEmpty = transform:Find("contentRoot/noEmpty")
    self.add = transform:Find("contentRoot/noEmpty/add").gameObject
    self.content = transform:Find("contentRoot/noEmpty/Scroll View/Viewport/Content"):GetComponent("Image")
end