---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xuyafang.
--- DateTime: 2018/11/19 15:20
---
LabInventionLineItem = class('LabInventionLineItem')
LabInventionLineItem.static.CHANGE_GREEN = "#0B7B16"  --改变量的绿色数值
LabInventionLineItem.static.CHANGE_RED = "#E42E2E"

--初始化方法
function LabInventionLineItem:initialize(data, viewRect)
    self.viewRect = viewRect
    self.data = data

    local viewTrans = self.viewRect
    self.nameText = viewTrans:Find("Text"):GetComponent("Text")
    self.nameText.text = data.itemId
    --self.iconImg = viewTrans:Find("name/iconBg/Image"):GetComponent("Image")
    --self.collectBtn = viewTrans:Find("name/collectRoot/btn"):GetComponent("Button")

    --self:_initData()
    --
    --self.collectBtn.onClick:RemoveAllListeners()
    --self.collectBtn.onClick:AddListener(function ()
    --    self:_clickCollectBtn()
    --end)
    --self.exchangeBtn.onClick:RemoveAllListeners()
    --self.exchangeBtn.onClick:AddListener(function ()
    --    self:_clickExchnageBtn()
    --end)
    --if self.detailBtn ~= nil then
    --    self.detailBtn.onClick:RemoveAllListeners()
    --    self.detailBtn.onClick:AddListener(function ()
    --        self:_clickDetailBtn()
    --    end)
    --end
end

--初始化界面
function LabInventionLineItem:_initData()
    ---配合pb数据
    local data = self.data
    self:_setCollectState(data.isCollected)
    self.nameText.text = data.name
    self.lastPriceText.text = "E"..getPriceString(data.nowPrice, 30, 24)
    if data.priceChange >= 0 then
        self.changeText.text = string.format("<color=%s>+%6.2f%%</color>", LabInventionLineItem.static.CHANGE_GREEN, data.priceChange)
        --设置箭头位置
        self.lastPriceGreenTran.localScale = Vector3.one
        self.lastPriceRedTran.localScale = Vector3.zero
        local greenPos = self.lastPriceGreenTran.localPosition
        self.lastPriceGreenTran.localPosition = Vector3.New(-63 + self.lastPriceText.preferredWidth, greenPos.y, greenPos.z)
    else
        self.changeText.text = string.format("<color=%s>%6.2f%%</color>", LabInventionLineItem.static.CHANGE_RED, data.priceChange)
        --设置箭头位置
        self.lastPriceGreenTran.localScale = Vector3.zero
        self.lastPriceRedTran.localScale = Vector3.one
        local redPos = self.lastPriceRedTran.localPosition
        self.lastPriceRedTran.localPosition = Vector3.New(-63 + self.lastPriceText.preferredWidth, redPos.y, redPos.z)
    end

    self.highText.text = "E"..data.highPrice
    self.lowText.text = "E"..data.lowPrice
    self.volumeText.text = "E"..data.sumDealedPrice
end
--点击交易按钮
function LabInventionLineItem:_clickExchnageBtn()
    ct.OpenCtrl("ExchangeTransactionCtrl", self.data)
end