---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by password.
--- DateTime: 2019/8/27 15:04
---City Technology Level
CityLevel = {
    [1] = {
        lv = 1,
        exp = 1000,
        salary = 1000000,
        inventCount = 0,
    },
    [2] = {
        lv = 2,
        exp = 2000,
        salary = 2000000,
        inventCount = 1,
    },
    [3] = {
        lv = 3,
        exp = 4000,
        salary = 3000000,
        inventCount = 1,
    },
    [4] = {
        lv = 4,
        exp = 7000,
        salary = 4000000,
        inventCount = 0,
    },
    [5] = {
        lv = 5,
        exp = 11000,
        salary = 5000000,
        inventCount = 0,
    },
    [6] = {
        lv = 6,
        exp = 16000,
        salary = 6000000,
        inventCount = 0,
    },
    [7] = {
        lv = 7,
        exp = 22000,
        salary = 7000000,
        inventCount = 0,
    },
    [8] = {
        lv = 8,
        exp = 29000,
        salary = 8000000,
        inventCount = 0,
    },
    [9] = {
        lv = 9,
        exp = 37000,
        salary = 9000000,
        inventCount = 0,
    },
    [10] = {
        lv = 10,
        exp = 46000,
        salary = 10000000,
        inventCount = 0,
    },
    [11] = {
        lv = 11,
        exp = 56000,
        salary = 11000000,
        inventCount = 0,
    },
    [12] = {
        lv = 12,
        exp = 67000,
        salary = 12000000,
        inventCount = 0,
    },
    [13] = {
        lv = 13,
        exp = 79000,
        salary = 13000000,
        inventCount = 0,
    },
    [14] = {
        lv = 14,
        exp = 92000,
        salary = 14000000,
        inventCount = 0,
    },
    [15] = {
        lv = 15,
        exp = 106000,
        salary = 15000000,
        inventCount = 0,
    },
}