---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by password.
--- DateTime: 2019/1/11 14:48
---非建筑打开model的insid
OpenModelInsID = {
    ["LoginCtrl"] = 1,
    ["ServerListCtrl"] = 2,
    ["CreateRoleCtrl"] = 3,
    ["GameMainInterfaceCtrl"] = 4,
    ["CenterWareHouseCtrl"] = 5,
    ["ChooseWarehouseCtrl"] = 6,
    ["GameNoticeCtrl"] = 7,
    ["ChatCtrl"] = 8,
    ["FriendsCtrl"] = 9,
    ["CompanyCtrl"] = 10,
    ["GuildListCtrl"] = 11,
    ["GuildOwnCtrl"] = 12,
    ["GuildMessageCtrl"] = 13,
    ["GuildApplyCtrl"] = 14,
    ["AvtarCtrl"] = 15,
    ["BubbleMessageCtrl"] = 16,
    ["VolumeCtrl"] = 17,
    ["HistoryCurveCtrl"] = 18,
    ["BuildingInfoId"] = 19,
    ["EvaCtrl"] = 20,
}