SystemMapConversionConfig = {
    [2000100] ={
        ["typeName"] ="横路",
        ["BlockDatasValue"] = -2,
        ["prefabRoute"] = "Building/SystemRoad1",
        ["poolName"] = "SystemRoad1",
        ["x"] = 1 ,
        ["y"] = 1 ,
    },
    [2000200] = {
        ["typeName"] ="竖路",
        ["BlockDatasValue"] = -3,
        ["prefabRoute"] = "Building/SystemRoad2",
        ["poolName"] = "SystemRoad2",
        ["x"] = 1 ,
        ["y"] = 1 ,
    },
    [2000115] = {
        ["typeName"] ="十字路",
        ["BlockDatasValue"] = -4,
        ["prefabRoute"] = "Building/SystemRoad3",
        ["poolName"] = "SystemRoad3",
        ["x"] = 1 ,
        ["y"] = 1 ,
    },
    [2000103] = {
        ["typeName"] ="转角路1",
        ["BlockDatasValue"] = -5,
        ["prefabRoute"] = "Building/SystemRoad4",
        ["poolName"] = "SystemRoad4",
        ["x"] = 1 ,
        ["y"] = 1 ,
    },
    [2000106] = {
        ["typeName"] ="转角路2",
        ["BlockDatasValue"] = -6,
        ["prefabRoute"] = "Building/SystemRoad5",
        ["poolName"] = "SystemRoad5",
        ["x"] = 1 ,
        ["y"] = 1 ,
    },
    [2000112] = {
        ["typeName"] ="转角路3",
        ["BlockDatasValue"] = -7,
        ["prefabRoute"] = "Building/SystemRoad6",
        ["poolName"] = "SystemRoad6",
        ["x"] = 1 ,
        ["y"] = 1 ,
    },
    [2000109] = {
        ["typeName"] ="转角路4",
        ["BlockDatasValue"] = -8,
        ["prefabRoute"] = "Building/SystemRoad7",
        ["poolName"] = "SystemRoad7",
        ["x"] = 1 ,
        ["y"] = 1 ,
    },
    [2000107] = {
        ["typeName"] ="三岔路1",
        ["BlockDatasValue"] = -9,
        ["prefabRoute"] = "Building/SystemRoad8",
        ["poolName"] = "SystemRoad8",
        ["x"] = 1 ,
        ["y"] = 1 ,
    },
    [2000114] ={
        ["typeName"] ="三岔路2",
        ["BlockDatasValue"] = -10,
        ["prefabRoute"] = "Building/SystemRoad9",
        ["poolName"] = "SystemRoad9",
        ["x"] = 1 ,
        ["y"] = 1 ,
    },
    [2000113] = {
        ["typeName"] ="三岔路3",
        ["BlockDatasValue"] = -11,
        ["prefabRoute"] = "Building/SystemRoad10",
        ["poolName"] = "SystemRoad10",
        ["x"] = 1 ,
        ["y"] = 1 ,
    },
    [2000111] = {
        ["typeName"] ="三岔路4",
        ["BlockDatasValue"] = -12,
        ["prefabRoute"] = "Building/SystemRoad11",
        ["poolName"] = "SystemRoad11",
        ["x"] = 1 ,
        ["y"] = 1 ,
    },
    [2000500] = {
        ["typeName"] ="中心建筑",
        ["BlockDatasValue"] = -13,
        ["prefabRoute"] = "Building/Centralbuilding",
        ["poolName"] = "Centralbuilding",
        ["x"] = 5 ,
        ["y"] = 5 ,
    },
    [2000501] = {
        ["typeName"] ="机场",
        ["BlockDatasValue"] = -14,
        ["prefabRoute"] = "Building/Airport",
        ["poolName"] = "Airport",
        ["x"] = 4 ,
        ["y"] = 4 ,
    },
    [2000502] = {
        ["typeName"] ="港口",
        ["BlockDatasValue"] = -15,
        ["prefabRoute"] = "Building/Prot",
        ["poolName"] = "Port",
        ["x"] = 4 ,
        ["y"] = 4 ,
    },
    [2000503] = {
        ["typeName"] ="学校",
        ["BlockDatasValue"] = -16,
        ["prefabRoute"] = "Building/University",
        ["poolName"] = "University",
        ["x"] = 3 ,
        ["y"] = 3 ,
    },
    [2000504] = {
        ["typeName"] ="钟楼",
        ["BlockDatasValue"] = -17,
        ["prefabRoute"] = "Building/ClockTower",
        ["poolName"] = "BellTower",
        ["x"] = 2 ,
        ["y"] = 2 ,
    },
    [2000505] = {
        ["typeName"] ="博物馆",
        ["BlockDatasValue"] = -18,
        ["prefabRoute"] = "Building/Museum",
        ["poolName"] = "Museum",
        ["x"] = 3 ,
        ["y"] = 3 ,
    },
}