---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by password.
--- DateTime: 2019/8/10 17:35
---城市信息Model
CityInfoModel = class("CityInfoModel",ModelBase)
local pbl = pbl

function CityInfoModel:initialize(insId)
    self.insId = insId
    self:OnCreate()
end

function CityInfoModel:OnCreate()
    DataManager.RegisterErrorNetMsg()
    --网络回调
    DataManager.ModelRegisterNetMsg(nil,"gscode.OpCode","eachTypeNpcNum","gs.EachTypeNpcNum",self.n_OnGetNpcNum,self) --npc类型数量
    DataManager.ModelRegisterNetMsg(nil,"gscode.OpCode","getPlayerAmount","gs.PlayerAmount",self.n_OnPlayerCountCurve,self) --玩家数量
    DataManager.ModelRegisterNetMsg(nil,"sscode.OpCode","queryIndustryIncome","ss.IndustryIncome",self.n_OnIndustryIncome,self)
    DataManager.ModelRegisterNetMsg(nil,"gscode.OpCode","querySupplyAndDemand","gs.SupplyAndDemand",self.n_OnSupplyAndDemand,self)
    DataManager.ModelRegisterNetMsg(nil,"gscode.OpCode","queryIndustryTopInfo","gs.IndustryTopInfo",self.n_OnIndustryTopInfo,self)
    DataManager.ModelRegisterNetMsg(nil,"sscode.OpCode","queryGroundOrApartmentAvgPrice","ss.AverageTransactionprice",self.n_OnAvgPrice,self)
    DataManager.ModelRegisterNetMsg(nil,"sscode.OpCode","queryCityTransactionAmount","ss.CityTransactionAmount",self.n_OnTransactionAmount,self)
    DataManager.ModelRegisterNetMsg(nil,"sscode.OpCode","queryCityMoneyPool","ss.CityTransactionAmount",self.n_OnMoneyPool,self)  --历史
    DataManager.ModelRegisterNetMsg(nil,"gscode.OpCode","queryMoneyPoolInfo","gs.MoneyPool",self.n_OnMoneyPoolInfo,self)  --今日
    DataManager.ModelRegisterNetMsg(nil,"gscode.OpCode","queryRegalRanking","gs.RegalRanking",self.n_OnRanking,self)
    DataManager.ModelRegisterNetMsg(nil,"gscode.OpCode","queryCityLevel","gs.CityLevel",self.n_OnLevel,self)

end

function CityInfoModel:Close()
    --清空本地UI事件
    DataManager.ModelRemoveNetMsg(nil,"gscode.OpCode","eachTypeNpcNum","gs.EachTypeNpcNum",self.n_OnGetNpcNum,self)
    DataManager.ModelRemoveNetMsg(nil,"gscode.OpCode","getPlayerAmount","gs.PlayerAmount",self.n_OnPlayerCountCurve,self)
    DataManager.ModelRemoveNetMsg(nil,"sscode.OpCode","queryIndustryIncome","ss.IndustryIncome",self.n_OnIndustryIncome,self)
    DataManager.ModelRemoveNetMsg(nil,"gscode.OpCode","querySupplyAndDemand","gs.SupplyAndDemand",self.n_OnSupplyAndDemand,self)
    DataManager.ModelRemoveNetMsg(nil,"gscode.OpCode","queryIndustryTopInfo","gs.IndustryTopInfo",self.n_OnIndustryTopInfo,self)
    DataManager.ModelRemoveNetMsg(nil,"sscode.OpCode","queryGroundOrApartmentAvgPrice","ss.AverageTransactionprice",self.n_OnAvgPrice,self)
    DataManager.ModelRemoveNetMsg(nil,"sscode.OpCode","queryCityTransactionAmount","ss.CityTransactionAmount",self.n_OnTransactionAmount,self)
    DataManager.ModelRemoveNetMsg(nil,"sscode.OpCode","queryCityMoneyPool","ss.CityTransactionAmount",self.n_OnMoneyPool,self)
    DataManager.ModelRemoveNetMsg(nil,"gscode.OpCode","queryMoneyPoolInfo","gs.MoneyPool",self.n_OnMoneyPoolInfo,self)
    DataManager.ModelRemoveNetMsg(nil,"gscode.OpCode","queryRegalRanking","gs.RegalRanking",self.n_OnRanking,self)
    DataManager.ModelRemoveNetMsg(nil,"gscode.OpCode","queryCityLevel","gs.CityLevel",self.n_OnLevel,self)

end
--客户端请求--

--获取npc数量
function CityInfoModel:m_GetNpcNum()
    local msgId = pbl.enum("gscode.OpCode","eachTypeNpcNum")
    CityEngineLua.Bundle:newAndSendMsg(msgId,nil)
end

--获取玩家数量
function CityInfoModel:m_GetPlayerNum()
    local msgId = pbl.enum("gscode.OpCode","getPlayerAmount")
    CityEngineLua.Bundle:newAndSendMsg(msgId,nil)
end

--查询行业收入
function CityInfoModel:m_queryIndustryIncome()
    local msgId = pbl.enum("sscode.OpCode","queryIndustryIncome")
    CityEngineLua.Bundle:newAndSendMsgExt(msgId, nil, CityEngineLua._tradeNetworkInterface1)
end

--查詢行业供需
function CityInfoModel:m_querySupplyAndDemand(type)
    DataManager.ModelSendNetMes("gscode.OpCode", "querySupplyAndDemand","gs.SupplyAndDemand",{type = type})
end

--查询行业排行
function CityInfoModel:m_queryIndustryTopInfo(ownerId,type)
    DataManager.ModelSendNetMes("gscode.OpCode", "queryIndustryTopInfo","gs.QueryIndustry",{pid = ownerId,type = type})
end

--查询成交均价
function CityInfoModel:m_queryAvgPrice(bool)
    local msgId = pbl.enum("sscode.OpCode","queryGroundOrApartmentAvgPrice")
    local lMsg = { b = bool }
    local pMsg = assert(pbl.encode("gs.Bool", lMsg))
    CityEngineLua.Bundle:newAndSendMsgExt(msgId, pMsg, CityEngineLua._tradeNetworkInterface1)
end

--查询全城销售额
function CityInfoModel:m_queryTransactionAmount(bool)
    local msgId = pbl.enum("sscode.OpCode","queryCityTransactionAmount")
    local lMsg = { b = bool }
    local pMsg = assert(pbl.encode("gs.Bool", lMsg))
    CityEngineLua.Bundle:newAndSendMsgExt(msgId, pMsg, CityEngineLua._tradeNetworkInterface1)
end

--查询全城奖金池（今日）
function CityInfoModel:m_queryMoneyPoolInfo()
    local msgId = pbl.enum("gscode.OpCode","queryMoneyPoolInfo")
    CityEngineLua.Bundle:newAndSendMsg(msgId,nil)
end

--查询全城奖金池(历史)
function CityInfoModel:m_queryMoneyPool()
    local msgId = pbl.enum("sscode.OpCode","queryCityMoneyPool")
    CityEngineLua.Bundle:newAndSendMsgExt(msgId, pMsg, CityEngineLua._tradeNetworkInterface1)
end

--查询排行榜
function CityInfoModel:m_queryRanking(playerId)
    DataManager.ModelSendNetMes("gscode.OpCode", "queryRegalRanking","gs.Id",{id = playerId})
end

--查询等级
function CityInfoModel:m_queryLevel()
    local msgId = pbl.enum("gscode.OpCode","queryCityLevel")
    CityEngineLua.Bundle:newAndSendMsg(msgId,nil)
end

--服务器回调

--npc类型数量
function CityInfoModel:n_OnGetNpcNum(info)
    DataManager.ControllerRpcNoRet(self.insId,"CityInfoCtrl", 'c_NpcNum',info)
end

--玩家数量
function CityInfoModel:n_OnPlayerCountCurve(lMsg)
    DataManager.ControllerRpcNoRet(self.insId,"CityInfoCtrl", 'c_PlayerNum',lMsg.playerAmount)
end

--行业收入
function CityInfoModel:n_OnIndustryIncome(info)
    DataManager.ControllerRpcNoRet(self.insId,"CityInfoCtrl", '_receiveIndustryIncome',info)
end

--行业供需
function CityInfoModel:n_OnSupplyAndDemand(info)
    DataManager.ControllerRpcNoRet(self.insId,"CityInfoCtrl", '_receiveSupplyAndDemand',info)
end

--行业排行
function CityInfoModel:n_OnIndustryTopInfo(info)
    DataManager.ControllerRpcNoRet(self.insId,"CityInfoCtrl", '_receiveIndustryTopInfo',info)
end

--成交均价
function CityInfoModel:n_OnAvgPrice(info)
    DataManager.ControllerRpcNoRet(self.insId,"CityInfoCtrl", '_receiveAvgPrice',info)
end

--全城销售额
function CityInfoModel:n_OnTransactionAmount(info)
    if info.flag then  --历史
        DataManager.ControllerRpcNoRet(self.insId,"CityVolumeCtrl", '_receiveTransactionAmount',info.amount)
    else  --今日
        DataManager.ControllerRpcNoRet(self.insId,"CityInfoCtrl", '_receiveTransactionAmount',info.amount)
    end
end

--全城奖金池(历史)
function CityInfoModel:n_OnMoneyPool(info)
    DataManager.ControllerRpcNoRet(self.insId,"CityVolumeCtrl", '_receiveMoneyPool',info.amount)
end

--全城奖金池(今日)
function CityInfoModel:n_OnMoneyPoolInfo(info)
    DataManager.ControllerRpcNoRet(self.insId,"CityInfoCtrl", '_receiveMoneyPoolInfo',info)
end

--排行榜
function CityInfoModel:n_OnRanking(info)
    DataManager.ControllerRpcNoRet(self.insId,"CityRickListCtrl", '_receiveRanking',info)
end

--等级
function CityInfoModel:n_OnLevel(info)
    DataManager.ControllerRpcNoRet(self.insId,"CityInfoCtrl", '_receiveLevel',info)
end

