---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Tina.
--- DateTime: 2019/1/17 17:34
---

CompanyModel = class("CompanyModel",ModelBase)

function CompanyModel:initialize(insId)
    self.insId = insId
    self:OnCreate()
end

function CompanyModel:OnCreate()
    DataManager.ModelRegisterNetMsg(nil,"gscode.OpCode","getGroundInfo","gs.GroundChange",self.n_OnGetGroundInfo,self)
    DataManager.ModelRegisterNetMsg(nil,"gscode.OpCode","queryMyBuildings","gs.MyBuildingInfos",self.n_OnQueryMyBuildings,self)
    --DataManager.ModelRegisterNetMsg(nil,"gscode.OpCode","queryMyEva","gs.Evas",self.n_OnQueryMyEva,self)
    --DataManager.ModelRegisterNetMsg(nil,"gscode.OpCode","updateMyEva","gs.Eva",self.n_OnUpdateMyEva,self)
    DataManager.ModelRegisterNetMsg(nil,"sscode.OpCode","queryPlayerIncomePayCurve","ss.PlayerIncomePayCurve",self.n_OnQueryPlayerIncomePayCurve,self)
    DataManager.ModelRegisterNetMsg(nil,"gscode.OpCode","modifyCompanyName","gs.RoleInfo",self.n_OnModifyCompanyName,self)
    DataManager.ModelRegisterNetMsg(nil,"gscode.OpCode","queryMyBrands","gs.MyBrands",self.n_OnQueryMyBrands,self)
    DataManager.ModelRegisterNetMsg(nil,"gscode.OpCode","modyfyMyBrandName","gs.ModyfyMyBrandName",self.n_OnModyfyMyBrandName,self)
end

-- Check player's land news
function CompanyModel:m_GetGroundInfo()
    --local msgId = pbl.enum("gscode.OpCode","getGroundInfo")
    --CityEngineLua.Bundle:newAndSendMsg(msgId, nil)
    DataManager.ModelSendNetMes("gscode.OpCode", "getGroundInfo","gs.Id",{id = CompanyCtrl.static.companyMgr:GetId()})
end

-- Land message returned by server
function CompanyModel:n_OnGetGroundInfo(groundInfos)
    Event.Brocast("c_OnGetGroundInfo", groundInfos)
end

-- Query player's building information
function CompanyModel.m_QueryMyBuildings()
    DataManager.ModelSendNetMes("gscode.OpCode", "queryMyBuildings","gs.QueryMyBuildings",{id = CompanyCtrl.static.companyMgr:GetId()})
end

-- Building information returned by the server
function CompanyModel:n_OnQueryMyBuildings(buildingInfos)
    Event.Brocast("c_OnQueryMyBuildings", buildingInfos)
end

-- Query player's Eva information
--function CompanyModel.m_QueryMyEva()
--    DataManager.ModelSendNetMes("gscode.OpCode", "queryMyEva","gs.Id",{id = DataManager.GetMyOwnerID()})
--end

-- Eva information returned by the server
--function CompanyModel:n_OnQueryMyEva(evas)
--    Event.Brocast("c_OnQueryMyEva", evas)
--end

-- Eva plus
--function CompanyModel:m_UpdateMyEva(eva)
--    DataManager.ModelSendNetMes("gscode.OpCode", "updateMyEva","gs.Eva",eva)
--end

-- Dot the Eva returned by the server
--function CompanyModel:n_OnUpdateMyEva(eva)
--    Event.Brocast("c_OnUpdateMyEva", eva)
--end

-- Query player's income and expenditure information
function CompanyModel.m_QueryPlayerIncomePayCurve()
    local msgId = pbl.enum("sscode.OpCode","queryPlayerIncomePayCurve")
    local lMsg = { id = CompanyCtrl.static.companyMgr:GetId() }
    local pMsg = assert(pbl.encode("ss.Id", lMsg))
    CityEngineLua.Bundle:newAndSendMsgExt(msgId, pMsg, CityEngineLua._tradeNetworkInterface1)
end

-- Graph information returned by the server
function CompanyModel:n_OnQueryPlayerIncomePayCurve(curveInfo)
    Event.Brocast("c_OnQueryPlayerIncomePayCurve", curveInfo)
end

-- Rename the company
function CompanyModel:m_ModifyCompanyName(companyName)
    DataManager.ModelSendNetMes("gscode.OpCode", "modifyCompanyName","gs.ModifyCompanyName",companyName)
end

-- Change of company name
function CompanyModel:n_OnModifyCompanyName(roleInfo, msgId)
    --Exception handling
    if msgId == 0 then
        if roleInfo.reason == "roleNameDuplicated"then
            Event.Brocast("SmallPop",GetLanguage(18010011),80)
        elseif roleInfo.reason == "accountInFreeze"then
            Event.Brocast("SmallPop",GetLanguage(18010012),80)
        end
        return
    end
    Event.Brocast("c_OnModifyCompanyName", roleInfo)
end

-- Query brand
function CompanyModel:m_QueryMyBrands()
    DataManager.ModelSendNetMes("gscode.OpCode", "queryMyBrands","gs.QueryMyBrands", {pId = CompanyCtrl.static.companyMgr:GetId()})
end

-- Query brand returns
function CompanyModel:n_OnQueryMyBrands(MyAllBrands)
    Event.Brocast("c_OnMQueryMyBrands", MyAllBrands)
end

-- Rebranding
function CompanyModel:m_ModyfyMyBrandName(brandLeague)
    DataManager.ModelSendNetMes("gscode.OpCode", "modyfyMyBrandName","gs.ModyfyMyBrandName", brandLeague)
end

-- Change the name of the brand
function CompanyModel:n_OnModyfyMyBrandName(modyfyMyBrandName, msgId)
    --Exception handling
    if msgId == 0 then
        if modyfyMyBrandName.reason == "roleNameDuplicated"then
            Event.Brocast("SmallPop","品牌名字重复！",80)
        end
        return
    end
    if modyfyMyBrandName.lastChangeTime then
        local timeTable = getFormatUnixTime(modyfyMyBrandName.lastChangeTime/1000)
        local time = timeTable.year .. "-" .. timeTable.month .. "-" ..timeTable.day
        -- Open prompt
        local info = {}
        info.titleInfo = "PROMPT"
        info.contentInfo = string.format("Last modified:<color=%s>%s</color>", "#3CF7FE",time)
        info.tipInfo = string.format("Cannot be modified within <color=%s>%s</color>!", "#FFE50B","7 days")
        ct.OpenCtrl("CompanyTipsCtrl", info)
        return
    end
    Event.Brocast("c_OnModyfyMyBrandName", modyfyMyBrandName)
end