---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xuyafang.
--- DateTime: 2018/9/4 16:56
---
local transform

BuildingInfoRightPanel = {};
local this = BuildingInfoRightPanel;

function BuildingInfoRightPanel.Awake(obj)
    transform = obj.transform;

    this.InitPanel();
    logDebug("右侧信息界面 Awake lua--->>"..transform.name);
end

function BuildingInfoRightPanel.InitPanel()
    this.sizeText = transform:Find("bg/infoRoot/size/text").gameObject:GetComponent("Text");  --Building size
    this.buildTimeText = transform:Find("bg/infoRoot/buildTime/text").gameObject:GetComponent("Text");  --Construction time
    this.usedTimeText = transform:Find("bg/infoRoot/usedTime/text").gameObject:GetComponent("Text");  --Elapsed time
    this.oldPercentText = transform:Find("bg/infoRoot/oldPercent/text").gameObject:GetComponent("Text");  --Depreciation

    this.initPanelFinish = true
end

--Set parent object and position
function BuildingInfoRightPanel.SetParentTran(parentTran)
    transform:SetParent(parentTran)
    transform.localPosition = Vector3.zero
end

--Display the information on the right
function BuildingInfoRightPanel.InitData(buildRightData)
    this.sizeText.text = buildRightData.width.."x"..buildRightData.height
    this.buildTimeText.text = buildRightData.buildTime
    this.usedTimeText.text = buildRightData.usedTime
    this.oldPercentText.text = buildRightData.oldPercent
end

--Change of face information - time used & depreciation
function BuildingInfoRightPanel.UpdateInfo(updateInfo)
    this.oldPercentText.text = updateInfo.oldPercent
    this.usedTimeText.text = updateInfo.usedTime
end
