---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by password.
--- DateTime: 2018/12/25 10:16
---专家panel
local transform
ExpertPanel = {}
local this = ExpertPanel

function ExpertPanel.Awake(obj)
    transform = obj.transform
    this.InitPanel()
end

function ExpertPanel.InitPanel()
    this.backBtn = transform:Find("top/BackBtn").gameObject
    this.name = transform:Find("down/TalentsCardItem/iocn/name"):GetComponent("Text")
    this.buildingText = transform:Find("down/TalentsCardItem/state/buildingText"):GetComponent("Text")
    this.content = transform:Find("down/TalentsCardItem/Scroll View/Viewport/Content")
    this.dailywageText = transform:Find("down/TalentsCardItem/dayWage/dailywageText"):GetComponent("Text")--日工资
    this.workingText = transform:Find("down/TalentsCardItem/workTime/workingText"):GetComponent("Text")--工作时间
    this.tradTimeText = transform:Find("down/TalentsCardItem/tradTime/tradTimeText"):GetComponent("Text")--剩余时间
    this.relieve = transform:Find("down/TalentsCardItem/relieve").gameObject--解除合约
    this.recall = transform:Find("down/TalentsCardItem/recall").gameObject--召回

    this.addBtn = transform:Find("down/TalentsBlankItem/addBtn").gameObject--添加人才


end