---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xuyafang.
--- DateTime: 2018/9/21 10:25
---
-----
local transform
FlightChooseFlightPanel = {}
local this = FlightChooseFlightPanel

function FlightChooseFlightPanel.Awake(obj)
    transform = obj.transform
    this.InitPanel()
end

function FlightChooseFlightPanel.InitPanel()
    this.backBtn = transform:Find("topRoot/backBtn")

    this.timeText = transform:Find("placeRoot/timeText"):GetComponent("Text")  --time
    this.startCodeText = transform:Find("placeRoot/startCodeText"):GetComponent("Text")  --Starting code
    this.startPlaceText = transform:Find("placeRoot/startPlaceText"):GetComponent("Text")  --Starting place name
    this.endCodeText = transform:Find("placeRoot/endCodeText"):GetComponent("Text")
    this.endPlaceText = transform:Find("placeRoot/endPlaceText"):GetComponent("Text")

    this.prefab = transform:Find("itemRoot/ChooseFlightItem")
    this.scrollLoop = transform:Find("itemRoot/scroll"):GetComponent("VScrollLoopTool")

    this.titleText01 = transform:Find("topRoot/Text"):GetComponent("Text")
    this.valueText02 = transform:Find("itemRoot/01/Text"):GetComponent("Text")
    this.valueText03 = transform:Find("itemRoot/02/Text"):GetComponent("Text")
    this.valueText04 = transform:Find("itemRoot/03/Text"):GetComponent("Text")
    this.valueText05 = transform:Find("itemRoot/04/Text"):GetComponent("Text")
    this.valueText06 = transform:Find("itemRoot/05/Text"):GetComponent("Text")
    this.valueText07 = transform:Find("itemRoot/06/Text"):GetComponent("Text")
end