---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xuyafang.
--- DateTime: 2018/8/31 19:19
---
local transform
local gameObject

GroundAuctionPanel = {}
local this = GroundAuctionPanel

function GroundAuctionPanel.Awake(obj)
    gameObject = obj
    transform = obj.transform

    this.InitPanel()
end

--初始化面板--
function GroundAuctionPanel.InitPanel()
    this.backBtn = transform:Find("bgBtn")
    this.titleText = transform:Find("root/titleText"):GetComponent("Text")
    this.timeDownText = transform:Find("root/timeDownRoot/timeDownText"):GetComponent("Text")  --倒计时
    this.soonRoot = transform:Find("root/soon")
    this.soonStartTime = transform:Find("root/soon/startTime")
    this.soonPrice = transform:Find("root/soon/price")

    this.nowRoot = transform:Find("root/now")
    this.nowPrice = transform:Find("root/now/price")
    this.noneHistoryRoot = transform:Find("root/now/noneBid")
    this.bidInput = transform:Find("root/now/input"):GetComponent("InputField")
    this.bidBtn = transform:Find("root/now/bidBtn")

    this.historyRoot = transform:Find("root/now/historyRoot")
    this.historyContent = transform:Find("root/now/historyRoot/scrollRect/content")
    this.historyItemPrefab = transform:Find("root/now/historyRoot/GAucHistoryItem")

    this.hourText01 = transform:Find("root/timeDownRoot/Text01"):GetComponent("Text")
    this.minuteText02 = transform:Find("root/timeDownRoot/Text02"):GetComponent("Text")
    this.secondText03 = transform:Find("root/timeDownRoot/Text03"):GetComponent("Text")
    this.noneHistoryText04 = transform:Find("root/now/noneBid/noneBidText"):GetComponent("Text")
    this.tipText05 = transform:Find("root/now/tipText"):GetComponent("Text")
end
--拍卖中有没有人出价
function GroundAuctionPanel.setBidState(hasBid)
    if hasBid == true then
        this.historyRoot.localScale = Vector3.one
        this.noneHistoryRoot.localScale = Vector3.zero
    else
        this.historyRoot.localScale = Vector3.zero
        this.noneHistoryRoot.localScale = Vector3.one
    end
end
--拍卖中或者即将拍卖
function GroundAuctionPanel.setSoonAndNow(isNow)
    if isNow == true then
        this.soonRoot.localScale = Vector3.zero
        this.nowRoot.localScale = Vector3.one
    else
        this.soonRoot.localScale = Vector3.one
        this.nowRoot.localScale = Vector3.zero
    end
end