---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/12/21/021 16:10
---
local transform;

GuidBookPanel = {};
local this = GuidBookPanel;

function GuidBookPanel.Awake(obj)
    transform = obj.transform;
    this.InitPanel();
end

function GuidBookPanel.InitPanel()
    this.backBtn = transform:Find("bg/bg/topRoot/top/back");
    this.showCon= transform:Find("bg/bg/topRoot/Scroll View/Viewport/Content");
    this.buttonCon=transform:Find("bg/bg/bottonRoot/Scroll View/Viewport/Content");
end
--数据初始化
function GuidBookPanel.InitDate(MunicipalData)
    this.materialData = MunicipalData;
end





