---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by password.
--- DateTime: 2019/3/12 15:10
---Historical graph panel
local transform;
local gameObject;

HistoryCurvePanel = {};
local this = HistoryCurvePanel;

--Start event -
function HistoryCurvePanel.Awake(obj)
    gameObject = obj;
    transform = obj.transform;

    this.InitPanel();
    logWarn("Awake lua--->>"..gameObject.name);
end

--Initialization panel--
function HistoryCurvePanel.InitPanel()
    --top
    this.xBtn = transform:Find("history/xBtn").gameObject --return
    this.name = transform:Find("history/name"):GetComponent("Text");
    this.yScale = transform:Find("history/yScale"):GetComponent("RectTransform");  --Y axis
    this.quantity = transform:Find("history/yScale/quantity"):GetComponent("Text");
    this.date = transform:Find("history/xScale/Text"):GetComponent("Text");
    this.curve = transform:Find("history/curveBg/curve"):GetComponent("RectTransform");
    this.slide = transform:Find("history/curveBg/curve"):GetComponent("Slide");  --slide
    this.graph = transform:Find("history/curveBg/curve"):GetComponent("FunctionalGraph");  --Draw curve
    this.goods = transform:Find("history/downBg/goods/goodsImage"):GetComponent("Image")  --product picture
    this.goodsText = transform:Find("history/downBg/goods/goodsText"):GetComponent("Text")  --Product name
    this.reauirementText = transform:Find("history/downBg/reauirement/reauirementText"):GetComponent("Text")  --demand
    this.supplyText = transform:Find("history/downBg/supply/supplyText"):GetComponent("Text")  --supply
end