---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xuyafang.
--- DateTime: 2018/11/29 18:35
---
local transform
LabInventionPanel = {}
local this = LabInventionPanel

function LabInventionPanel.Awake(obj)
    transform = obj.transform
    this.InitPanel()
end

function LabInventionPanel.InitPanel()
    this.backBtn = transform:Find("topRoot/backBtn")
    this.emptyTextTran = transform:Find("bottomRoot/left/progressRoot/emptyText")  --还未点击研究时的显示
    this.workingRootTran = transform:Find("bottomRoot/left/progressRoot/workingRoot")  --灯泡显示的父物体
    this.phaseItems = LabInventionItemPhaseItems:new(transform:Find("bottomRoot/left/successItems"))

    this.itemNameText = transform:Find("bottomRoot/right/titleBg/itemNameText"):GetComponent("Text")
    this.iconImg = transform:Find("bottomRoot/right/iconImg"):GetComponent("Image")
    this.inventionBtn = transform:Find("bottomRoot/right/workingImg/inventionBtn")

    this.singleLineTran = transform:Find("bottomRoot/right/singleLine")
    this.singleLineItem = LabFormulaItem:new(this.singleLineTran)
    this.twoLineTran = transform:Find("bottomRoot/right/twoLine")
    this.twoLineItem = LabFormulaItem:new(this.twoLine)
    this.threeLineTran = transform:Find("bottomRoot/right/threeLine")
    this.threeLineItem = LabFormulaItem:new(this.threeLineTran)
    this.researchBtn = transform:Find("bottomRoot/workingImg/researchBtn")
end