---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by password.
--- DateTime: 2019/4/10 16:05
---推广公司曲线图
local transform;
local gameObject;

PromoteCurvePanel = {};
local this = PromoteCurvePanel;
--启动事件--
function PromoteCurvePanel.Awake(obj)
    gameObject = obj;
    transform = obj.transform;

    this.InitPanel();
    logWarn("Awake lua--->>"..gameObject.name);
end

--初始化面板--
function PromoteCurvePanel.InitPanel()
    this.back = transform:Find("bg").gameObject
    this.slide = transform:Find("contentBg/curveBg/curve"):GetComponent("Slide")
    this.graph = transform:Find("contentBg/curveBg/curve"):GetComponent("FunctionalGraph")
    this.yScale = transform:Find("contentBg/YScale"):GetComponent("RectTransform")
    this.goods = transform:Find("contentBg/signBg/goods"):GetComponent("Image")   --物品图片
    this.goodsText = transform:Find("contentBg/signBg/goods/goodsText"):GetComponent("Text")   --物品名字

end