---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Tina.
--- DateTime: 2019/7/25 14:59
---

local transform
ResearchOpenBoxPanel = {}

local this = ResearchOpenBoxPanel

function ResearchOpenBoxPanel.Awake(obj)
    transform = obj.transform
    this.InitPanel()
end

function ResearchOpenBoxPanel.InitPanel()
    this.backBtn = transform:Find("BackBtn").gameObject
    this.openBtn = transform:Find("MiddleRoot/OpenBtn").gameObject

    this.boxsScrollContent = transform:Find("LeftRoot/BoxsScroll/Viewport/Content")
    this.researchEvaBoxItem = transform:Find("LeftRoot/BoxsScroll/Viewport/Content/ResearchEvaBoxItem").gameObject
    this.totalNumText = transform:Find("LeftRoot/NumText"):GetComponent("Text")

    -- 开点
    this.middleRoot = transform:Find("MiddleRoot")
    this.subtractBtn = transform:Find("MiddleRoot/SubtractBtn").gameObject
    this.addBtn = transform:Find("MiddleRoot/AddBtn").gameObject
    this.inputField = transform:Find("MiddleRoot/InputField"):GetComponent("InputField")
    this.middleNumText = transform:Find("MiddleRoot/MiddleNumText"):GetComponent("Text")
    this.tipsText = transform:Find("MiddleRoot/TipsText"):GetComponent("Text")

    -- 开箱结果
    this.researchMaterialItem = transform:Find("ResearchMaterialItem")
    this.iconImage = transform:Find("ResearchMaterialItem/IconImage"):GetComponent("Image")
    this.resultNumText = transform:Find("ResearchMaterialItem/NumText"):GetComponent("Text")
    this.resultNameText = transform:Find("ResearchMaterialItem/NameText"):GetComponent("Text")
end