---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Tina.
--- DateTime: 2019/7/25 14:59
---

local transform
ResearchOpenBoxPanel = {}

local this = ResearchOpenBoxPanel

function ResearchOpenBoxPanel.Awake(obj)
    transform = obj.transform
    this.InitPanel()
end

function ResearchOpenBoxPanel.InitPanel()

end