---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by password.
--- DateTime: 2019/5/20 17:45
---设置密码panel
local transform;
local gameObject;

SetPasswordPanel = {};
local this = SetPasswordPanel;

--启动事件--
function SetPasswordPanel.Awake(obj)
    gameObject = obj;
    transform = obj.transform;
    this.InitPanel();
end

--初始化面板--
function SetPasswordPanel.InitPanel()
    this.name = transform:Find("name"):GetComponent('Text');

    this.password = transform:Find("password"):GetComponent('InputField');
    this.confirm = transform:Find("confirm"):GetComponent('InputField');

    this.passwordHint = transform:Find("password/hint"):GetComponent("Text");  --确认密码提示
    this.confirmHint = transform:Find("confirm/hint"):GetComponent("Text");  --确认密码提示

    this.back = transform:Find("back").gameObject; --返回
    this.next = transform:Find("next").gameObject;    --获取验证码
end
