---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/1/001 16:58
---

require "Common/define"

local transform;

SignOnPanel = {};
local this = SignOnPanel;

function SignOnPanel.Awake(obj)
    transform = obj.transform;

    this.InitPanel();
end

function SignOnPanel.InitPanel()
    this.rightRootTran = transform:Find("rightRoot");
    this.leftRootTran = transform:Find("leftRoot");
    this.topRootTran = transform:Find("topRoot");

    this.backBtn = transform:Find("topRoot/bg/backBtn");
    this.infoBtn = transform:Find("topRoot/bg/infoBtn");

    this.confirmBtn=transform:Find("BG/Image/confirm");

end
--数据初始化
function SignOnPanel.InitDate(AdvertisementPosData)
    this.materialData = AdvertisementPosData;
end
