---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/12/25/025 17:48
---

local transform;

StopAndBuildPanel = {};
local this = StopAndBuildPanel;

function StopAndBuildPanel.Awake(obj)
    transform = obj.transform;
    this.InitPanel();
end

function StopAndBuildPanel.InitPanel()
    this.backBtn=transform:Find("topRoot/backBtn")
    this.backBtn1=transform:Find("Button")
    this.groundInfoText=transform:Find("leftRoot/topRoot/landInfo/Text"):GetComponent("Text");
    this.personIma=transform:Find("leftRoot/topRoot/PersonInfo/Avtar/personIma"):GetComponent("Image");
    this.nameInp=transform:Find("leftRoot/topRoot/PersonInfo/nameInp"):GetComponent("InputField")
    this.commanyInp=transform:Find("leftRoot/topRoot/PersonInfo/commanyInp"):GetComponent("InputField")
---***********************************************************************************************************---
    this.greenBtn1=transform:Find("leftRoot/bottonRoot/Scroll View/Viewport/Content/Image1/Button")
    this.select1=transform:Find("leftRoot/bottonRoot/Scroll View/Viewport/Content/Image1/select")

    this.greenBtn2=transform:Find("leftRoot/bottonRoot/Scroll View/Viewport/Content/Image2/Button")
    this.select2=transform:Find("leftRoot/bottonRoot/Scroll View/Viewport/Content/Image2/select")

    this.greenBtn3=transform:Find("leftRoot/bottonRoot/Scroll View/Viewport/Content/Image3/Button")
    this.select3=transform:Find("leftRoot/bottonRoot/Scroll View/Viewport/Content/Image3/select")

    this.greenBtn4=transform:Find("leftRoot/bottonRoot/Scroll View/Viewport/Content/Image4/Button")
    this.select4=transform:Find("leftRoot/bottonRoot/Scroll View/Viewport/Content/Image4/select")

    this.greenBtn5=transform:Find("leftRoot/bottonRoot/Scroll View/Viewport/Content/Image5/Button")
    this.select5=transform:Find("leftRoot/bottonRoot/Scroll View/Viewport/Content/Image5/select")

    this.greenBtn6=transform:Find("leftRoot/bottonRoot/Scroll View/Viewport/Content/Image6/Button")
    this.select6=transform:Find("leftRoot/bottonRoot/Scroll View/Viewport/Content/Image6/select")

    this.greenBtn7=transform:Find("leftRoot/bottonRoot/Scroll View/Viewport/Content/Image7/Button")
    this.select7=transform:Find("leftRoot/bottonRoot/Scroll View/Viewport/Content/Image7/select")

    this.greenBtn8=transform:Find("leftRoot/bottonRoot/Scroll View/Viewport/Content/Image8/Button")
    this.select8=transform:Find("leftRoot/bottonRoot/Scroll View/Viewport/Content/Image8/select")

    this.greenBtn9=transform:Find("leftRoot/bottonRoot/Scroll View/Viewport/Content/Image9/Button")
    this.select9=transform:Find("leftRoot/bottonRoot/Scroll View/Viewport/Content/Image9/select")
  ------------************************* TODO:Left info **************************************---------------
    this.dateText=transform:Find("leftRoot/bottonRoot/infoRoot/tenancyRoot/nameText"):GetComponent("Text")
    this.date=transform:Find("leftRoot/bottonRoot/infoRoot/tenancyRoot/Text"):GetComponent("Text")

    this.dailyRentText=transform:Find("leftRoot/bottonRoot/infoRoot/daily/nameText"):GetComponent("Text")
    this.dailyRent=transform:Find("leftRoot/bottonRoot/infoRoot/daily/Text"):GetComponent("Text")

    this.depositText=transform:Find("leftRoot/bottonRoot/infoRoot/deposit/nameText"):GetComponent("Text")
    this.deposit=transform:Find("leftRoot/bottonRoot/infoRoot/deposit/Text"):GetComponent("Text")
    ------------************************* TODO:Right info **************************************---------------
    this.rightPerIma=transform:Find("rightRoot/topRoot/PersonInfo/Avtar/personIma"):GetComponent("Image")
    this.operatorText=transform:Find("rightRoot/topRoot/landInfo/Text"):GetComponent("Text");
    this.rightnameInp=transform:Find("rightRoot/topRoot/PersonInfo/nameInp"):GetComponent("InputField")
    this.rightcommanyInp=transform:Find("rightRoot/topRoot/PersonInfo/commanyInp"):GetComponent("InputField")
    this.scaleText=transform:Find("rightRoot/bottonRoot/infoRoot/scale/nameText"):GetComponent("Text");
    this.scale=transform:Find("rightRoot/bottonRoot/infoRoot/scale/Text"):GetComponent("Text");
    this.constructText=transform:Find("rightRoot/bottonRoot/infoRoot/construct/nameText"):GetComponent("Text");
    this.construct=transform:Find("rightRoot/bottonRoot/infoRoot/construct/Text"):GetComponent("Text");
    this.tips=transform:Find("rightRoot/bottonRoot/Panel/tips"):GetComponent("Text");
    this.stopBtn=transform:Find("rightRoot/bottonRoot/Panel/stop")
    this.removeBtn=transform:Find("rightRoot/bottonRoot/Panel/remove")
    this.stopIconRoot=transform:Find("stopIconROOT")
    this.stopText=transform:Find("stopIconROOT/Text"):GetComponent("Text")

end
--数据初始化
function StopAndBuildPanel.InitDate(MunicipalData)
    this.MunicipalData = MunicipalData;

end

function StopAndBuildPanel:CloseBtn()
    this.greenBtn1.localScale=Vector3.zero
    this.greenBtn2.localScale=Vector3.zero
    this.greenBtn3.localScale=Vector3.zero
    this.greenBtn4.localScale=Vector3.zero
    this.greenBtn5.localScale=Vector3.zero
    this.greenBtn6.localScale=Vector3.zero
    this.greenBtn7.localScale=Vector3.zero
    this.greenBtn8.localScale=Vector3.zero
    this.greenBtn9.localScale=Vector3.zero
    this.select1.localScale=Vector3.zero

end
